### ISSUE TITLE
Memory Usage Requirements

### ISSUE THREAD

**Issue by Kavar814** [mjoy0210/brainiac#1]
Utilizing the following header:
``#include <bits/stdc++.h>``
is not a safe practice for usable code and portable code usage due to the intensive memory requirements it has. Especially considering the nature of the purpose of your code, a BrainF*** interpreter, which is meant for a language that utilizes minimal memory consumption and therefore intrinsically must be sparse in its memory usage.  Therefore, I suggest utilizing less memory intensive methods, such as specific header files in order to conserve the memory used.

Furthermore, I would suggest utilizing comments in your code in order for ease of further development for other contributors to this project, or those who would like to fork or clone this repository.

Therefore, I suggest you:

> GET GUD M9

**Comment by mjoy0210** [comment]
"It's an implementation for precompiled headers. If you set it up for precompilation correctly it could in fact speed up compilation time depending on your project"

https://stackoverflow.com/questions/25311011/how-does-include-bits-stdc-h-work-in-c

**Comment by mjoy0210** [comment]
(When set up right)

**Comment by Kavar814** [comment]
Has this been implemented correctly?

**Comment by mjoy0210** [comment]
This product is under development, so this header is still being used for testing. It takes less time to implement into a program and it reduces the chance of errors.
